version: "3.9"
services:
  db:
    container_name: postgres_db
    image: postgres:14
    networks:
      - repeater_bot
    env_file:
      - default.env
    volumes:
      - ./pgdbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    container_name: fastapi_app
    build:
      dockerfile: Dockerfile.app
    networks:
      - repeater_bot
    links:
      - db
    env_file:
      - default.env
    ports:
      - 8000:8000

  tgbot:
    container_name: telegram_bot
    build:
      dockerfile: Dockerfile.tg
    networks:
      - repeater_bot
    links:
      - app
    env_file:
      - default.env
    ports:
      - 5000:5000

networks:
  repeater_bot:
